feature(Storage.Aliyun): add Alibaba Cloud Cloud Storage
masastack/MASA.Contrib pull request #34
Opened 2022-04-12 08:55 UTC by zhenlei520

### Chore
* Pm: Optimize the writing method of AddPmClient and add CallerOptions judgment

### Features
* Storage.Aliyun: add Alibaba Cloud Cloud Storage

2022-04-12 10:17 UTC, doddgu requested changes

2022-04-12 10:17 UTC, doddgu commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +    public Client(ALiYunStorageOptions options, IMemoryCache cache, ILogger<Client>? logger)
ALiYun -> Aliyun

2022-04-12 10:17 UTC, doddgu commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +        string accessKey,
accessKeyId

2022-04-12 10:17 UTC, doddgu commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +        string accessSecret,
accessKeySecret

2022-04-12 10:17 UTC, doddgu commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Options/ALiYunStorageOptions.cs
> +public class ALiYunStorageOptions
Amazing!

2022-04-12 10:17 UTC, doddgu commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.zh-CN.md
> +builder.Services.AddAliyunStorage(() => new ALiYunStorageOptions(configuration["Aliyun:AccessKey"], configuration["Aliyun:AccessSecret"], configuration["Aliyun:RegionId"], configuration["Aliyun:RoleA
amazing ALiYun

2022-04-12 10:49 UTC, zhenlei520 commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/README.zh-CN.md
> +builder.Services.AddAliyunStorage(() => new ALiYunStorageOptions(configuration["Aliyun:AccessKey"], configuration["Aliyun:AccessSecret"], configuration["Aliyun:RegionId"], configuration["Aliyun:RoleA
processed

2022-04-12 10:49 UTC, zhenlei520 commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Options/ALiYunStorageOptions.cs
> +public class ALiYunStorageOptions
processed

2022-04-12 10:50 UTC, zhenlei520 commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +        string accessSecret,
processed

2022-04-12 10:50 UTC, zhenlei520 commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +        string accessKey,
processed

2022-04-12 10:50 UTC, zhenlei520 commented on src/Storage/Masa.Contrib.Storage.ObjectStorage.Aliyun/Client.cs
> +    public Client(ALiYunStorageOptions options, IMemoryCache cache, ILogger<Client>? logger)
processed

2022-04-13 03:35 UTC, doddgu approved these changes
LGTM

2022-04-13 03:35 UTC, merged