docs: Modify the introduction of the homepage Readme
masastack/MASA.Contrib pull request #44
Opened 2022-04-20 11:05 UTC by zhenlei520

### Docs
* Homepage ReadMe: Modify the introduction of the homepage Readme
* CQRS: Modify the introduction of the Readme
* Isolation.MultiEnvironment: Modify the introduction of the Readme

2022-04-20 11:16 UTC, doddgu requested changes

2022-04-20 11:16 UTC, doddgu commented on README.md
> +## How to download
I think this not download

2022-04-20 11:16 UTC, doddgu commented on README.zh-CN.md
> +## 如何下载
I think this not 下载

2022-04-20 11:23 UTC, zhenlei520 commented on README.md
> +## How to download
How to Clone?

2022-04-20 11:23 UTC, zhenlei520 commented on README.zh-CN.md
> +## 如何下载
如何克隆？

2022-04-21 01:00 UTC, doddgu commented on README.zh-CN.md
> +## 如何下载
How to build or develop?

2022-04-21 01:01 UTC, doddgu approved these changes
LGTM

2022-04-21 01:01 UTC, merged