feat(tsc): add tsc integration with opentelemetry sdk
masastack/MASA.Contrib pull request #54
Opened 2022-05-10 10:23 UTC by Qinyouzeng

integrate opentelemetry sdk to collecter logging,tracing and metrcis
 - tracing supports: aspnetcore , entityframework and http 
 - metrcis supports: runtime , aspnetcore and http

2022-05-11 05:30 UTC, doddgu requested changes

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/README.zh-CN.md
> +builder.Services.AddMasaTracing(ops);
Use option pattern.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/StreamExtenistions.cs
> +            return null;
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/StreamExtenistions.cs
> +        return null;
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/ActivityExtensions.cs
> +        if (activity is null) return activity;
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/ActivityExtensions.cs
> +            activity.SetTag(OpenTelemetryAttributeName.Http.RequestContentBody, await httpRequest.HttpContext.Request.Body.ReadAsStringAsync(GetHttpRequestEncoding(httpRequest)));
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/ActivityExtensions.cs
> +        return null;
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/ActivityExtensions.cs
> +        if (activity is null) return activity;
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/ActivityExtensions.cs
> +            activity.AddTag(OpenTelemetryAttributeName.EndUser.Id, httpResponse.HttpContext.User.FindFirst("sub")?.Value ?? string.Empty);
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/AspNetCoreInstrumentationOptionsExtensions.cs
> +                return !_lstDefaultFilterIgnorePrefix.Any(prefix => httpContext.Request.Path.Value.StartsWith(prefix));
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/AspNetCoreInstrumentationOptionsExtensions.cs
> +                if (_lstBlazorFilterIgnorePrefix.Any(prefix => httpContext.Request.Path.Value.StartsWith(prefix)))
Warning: Possible null reference return.

2022-05-11 05:30 UTC, doddgu commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Tracing/AspNetCoreInstrumentationOptionsExtensions.cs
> +                if (_lstBlazorFilterIgnoreSuffix.Any(suffix => httpContext.Request.Path.Value.EndsWith(suffix)))
Warning: Possible null reference return.

2022-05-11 05:45 UTC, Qinyouzeng commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/MasaObservableOptions.cs
> +    public string ServerVersion { get; set; }
It's service version.

2022-05-11 06:05 UTC, Qinyouzeng commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/OpenTelemetryAttributeName.cs
> +namespace Masa.Contrib.Observability;
Change to Masa.Contrib.BasicAbility.Tsc.

2022-05-11 06:14 UTC, Qinyouzeng commented on src/BasicAbility/Masa.Contrib.BasicAbility.Tsc/Metrics/MasaServiceExtensions.cs
> +               .AddHttpClientInstrumentation();
Can use param `configure` type is `Action<MeterProviderBuilder>` , like this:
```
services.AddMasaMetrics(builder =>
{
    // add more instrumentation
    builder.AddCustomMetrics();
    builder.AddConsoleExporter();
}); 

```

2022-05-12 10:07 UTC, doddgu approved these changes
LGTM

2022-05-12 10:30 UTC, merged