feat: add BasicAbility dcc client and adjust dcc configuration directory
masastack/MASA.Contrib pull request #96
Opened 2022-06-23 10:02 UTC by codding-y

# Description

Add BasicAbility dcc client and adjust dcc configuration directory

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation

2022-06-24 01:29 UTC, zhenlei520 commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/ConfigurationApiClient.cs
> +                    var serializer = new SerializerBuilder().JsonCompatible().Build();
No need to initialize every time

2022-06-24 01:29 UTC, zhenlei520 commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Masa.Contrib.Configuration.ConfigurationApi.Dcc.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Must use `Newtonsoft.Json`

2022-06-24 01:29 UTC, zhenlei520 commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.md
> +    public string AppId { get; set; } = default!;
Does the local node need an AppId、ConfigObjects 、Secret 、Cluster ?

2022-06-24 01:29 UTC, zhenlei520 commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +}
same as above

2022-06-24 01:29 UTC, zhenlei520 commented on test/Masa.Contrib.BasicAbility.Dcc.Tests/Masa.Contrib.BasicAbility.Dcc.Tests/Masa.Contrib.BasicAbility.Dcc.Tests.csproj
> +  <ItemGroup>
using `Directory.Build.props`

2022-06-24 01:29 UTC, zhenlei520 commented on test/Masa.Contrib.BasicAbility.Pm.Tests/Masa.Contrib.BasicAbility.Pm.Tests.csproj
> +      <PrivateAssets>all</PrivateAssets>
using `Directory.Build.props`

2022-06-24 02:19 UTC, zhenlei520 commented on src/BasicAbility/Masa.Contrib.BasicAbility.Dcc/Masa.Contrib.BasicAbility.Dcc.csproj
> +    <PackageReference Include="Masa.Utils.Caching.Redis" Version="0.5.0-preview.3" />
using `Directory.Build.props`

2022-06-24 02:19 UTC, zhenlei520 commented on src/BasicAbility/Masa.Contrib.BasicAbility.Dcc/README.md
> +## Masa.Contrib.BasicAbility.Pm
Masa.Contrib.BasicAbility.Pm?

2022-06-24 03:45 UTC, codding-y commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Masa.Contrib.Configuration.ConfigurationApi.Dcc.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Subsequent planning will be abstracted

2022-06-24 05:24 UTC, zhenlei520 commented
@doddgu

2022-06-24 06:37 UTC, doddgu requested changes

2022-06-24 06:37 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Masa.Contrib.Configuration.ConfigurationApi.Dcc.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
Newtonsoft.Json???

2022-06-24 06:37 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +    //格式：ConfigurationAPI:<Replace-With-Your-AppId>:<Your Node Path>:<parameter name>
从配置中心获取指定AppId下的Name的配置值

2022-06-24 06:37 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +public class PlatformOptions : ConfigurationApiMasaConfigurationOptions
Platforms?

2022-06-27 01:24 UTC, doddgu requested changes

2022-06-27 06:33 UTC, codding-y commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +public class RedisOptions : ConfigurationApiMasaConfigurationOptions
This is an example. Take get the redis configuration as an example

2022-06-27 07:51 UTC, doddgu requested changes

2022-06-27 07:51 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Internal/Parser/XmlConfigurationParser.cs
> +            using var xmlSR = new StringReader(xmlStr);
xmlSR -> xmlStringReader or xmlSr

2022-06-27 07:51 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/Internal/Parser/XmlConfigurationParser.cs
> +        var JsonString = new StringBuilder();
JsonString -> json

2022-06-27 07:51 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +    return configuration["ConfigurationAPI:<Replace-With-Your-AppId>:Redis:Name"];
Name?

2022-06-27 07:51 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration/README.zh-CN.md
> +    return configuration["Local:Redis:Name"];
Host? Name? Be the same!

2022-06-27 08:05 UTC, doddgu requested changes

2022-06-27 08:05 UTC, doddgu commented on src/Configuration/Masa.Contrib.Configuration.ConfigurationApi.Dcc/README.zh-CN.md
> +    return configuration["ConfigurationAPI:<Replace-With-Your-AppId>:Redis:Host"];
You forget to update its en version?

2022-06-27 08:06 UTC, doddgu approved these changes
LGTM

2022-06-27 08:07 UTC, merged